FROM tiangolo/uwsgi-nginx:python3.6

COPY . .

RUN ls -al

run pwd

RUN pip install --upgrade pip && pip install -r requirements.txt

# URL under which static (not modified by Python) files will be requested
# They will be served by Nginx directly, without being handled by uWSGI
ENV STATIC_URL /static
# Absolute path in where the static files wil be
ENV STATIC_PATH /app/static

# If STATIC_INDEX is 1, serve / with /static/index.html directly (or the static URL configured)
# ENV STATIC_INDEX 1
ENV STATIC_INDEX 0

ENV FLASK_HOST=0.0.0.0
ENV FLASK_PORT=80
ENV UPLOAD_FOLDER=file_storage/
ENV STORAGE_BASE=storage/

# Move the base entrypoint to reuse it
RUN mv /entrypoint.sh /uwsgi-nginx-entrypoint.sh
# Copy the entrypoint that will generate Nginx additional configs
COPY scripts/entrypoint.sh /entrypoint.sh
COPY uwsgi/uwsgi.ini .
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# Run the start script provided by the parent image tiangolo/uwsgi-nginx.
# It will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Supervisor, which in turn will start Nginx and uWSGI
CMD ["/start.sh"]
